# Basic
title: Jenning
subtitle: 亲近自然，亲近所有美好。
welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: 嗨！我叫展宁（@Jenning），一名软件测试工程师。
creator: <a href="http://QAJenning.github.io">@Jenning</a>

url: "/"

permalink: /:year/:month/:title/

# Format
highlighter: plain

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: 博客
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Ford, description: My husband, url: 'http://smallfan.net/'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    #disqus: vno-jekyll
    duoshuo: jenning
    
# Social
social:
    # weibo: CoderSmallfan
    github: QAJenning
    #twitter: CoderSmallfan
    #gplus: 107108267983477358170
    mail: QAJenning@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
